# Generated by Django 4.0.1 on 2022-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('kewword', models.CharField(max_length=191)),
                ('address', models.CharField(max_length=191)),
                ('phone', models.CharField(max_length=191)),
                ('fax', models.CharField(blank=True, max_length=191)),
                ('email', models.EmailField(blank=True, max_length=191, null=True)),
                ('smtpserver', models.CharField(max_length=191)),
                ('smtpemail', models.CharField(blank=True, max_length=191, null=True)),
                ('smtppassword', models.CharField(blank=True, max_length=191, null=True)),
                ('smtpport', models.CharField(blank=True, max_length=191)),
                ('icon', models.ImageField(upload_to='icon')),
                ('facebook', models.CharField(blank=True, max_length=191)),
                ('instragram', models.CharField(blank=True, max_length=191)),
                ('contact', models.CharField(blank=True, max_length=191)),
                ('referece', models.TextField(blank=True, max_length=191)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
