# Generated by Django 4.0.1 on 2022-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=191)),
                ('quation', models.CharField(max_length=191)),
                ('answer', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
