# Generated by Django 4.0.1 on 2022-03-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_level_remove_category_lft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('code', models.CharField(editable=False, max_length=191)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=191)),
                ('city', models.CharField(blank=True, max_length=191)),
                ('country', models.CharField(blank=True, max_length=191)),
                ('tota', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Onshipping', 'Onshipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=191)),
                ('transaction_id', models.CharField(blank=True, max_length=191)),
                ('ip', models.CharField(blank=True, max_length=191)),
                ('transaction_image', models.ImageField(blank=True, upload_to='transaction_image/')),
                ('adminnote', models.CharField(blank=True, max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Onshipping', 'Onshipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
